[package]
name = "application"
version = "0.1.0"
authors = ["Niket Naidu <coder137@gmail.com>"]
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
l0 = { path = "../l0" }
l2 = { path = "../l2" }
l3 = { path = "../l3" }
l4 = { path = "../l4" }
